# Generated by Django 5.0.3 on 2026-04-27 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='daynote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_options', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nightevent',
            name='event_options',
            field=models.ManyToManyField(blank=True, related_name='night_events', to='care_tracking.eventoption'),
        ),
        migrations.AddField(
            model_name='nightevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='daynote',
            index=models.Index(fields=['user', 'date'], name='day_notes_user_id_97aa94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='daynote',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='eventoption',
            index=models.Index(fields=['user', 'is_active'], name='event_optio_user_id_04897e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventoption',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='nightevent',
            index=models.Index(fields=['user', 'event_datetime'], name='night_event_user_id_7fa46b_idx'),
        ),
        migrations.AddIndex(
            model_name='nightevent',
            index=models.Index(fields=['event_datetime'], name='night_event_event_d_bd311c_idx'),
        ),
    ]
