# Generated by Django 5.0.3 on 2026-05-27 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_tracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user whose records are being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='shares_given', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(help_text='The user who is allowed to view (read-only) the records.', on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Care Share',
                'verbose_name_plural': 'Care Shares',
                'db_table': 'care_shares',
                'ordering': ['owner', 'viewer'],
                'indexes': [models.Index(fields=['viewer'], name='care_shares_viewer__9d9600_idx'), models.Index(fields=['owner'], name='care_shares_owner_i_a57a85_idx')],
                'unique_together': {('owner', 'viewer')},
            },
        ),
    ]
