# Generated by Django 5.0.3 on 2026-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_group_night_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_email_last_sent',
            field=models.DateField(blank=True, help_text='Local date the last daily summary was sent, to avoid sending twice in one morning.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_email_time',
            field=models.TimeField(default='08:00:00', help_text='Time to send daily summary email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_night_events',
            field=models.BooleanField(default=False, help_text='Group events by night (5 PM - 10 AM) instead of calendar day'),
        ),
    ]
